return {
    modid   = 'Cryptid',
    prefix  = 'cry',
    content = {
        BanLists = {
            SuperBlinds = {
                'final_orb'
            },
            Overpowered = {
                'clock',
                'joke',
                'tax',
                'final_loop',
                'final_orb'
            },
        },
        JokerRanks = { },
        JokerSuits = { },
        JokerCategories = { -- sorted alphabetically because fuck
            ['adroit']          = { MadLib.JokerLists.Chips.Add },
            ['altgoogl']        = { MadLib.JokerLists.Sell, MadLib.JokerLists.Generative.Jokers },
            ['antennastoheaven']    = { MadLib.JokerLists.Sell, MadLib.JokerLists.Generative.Jokers },
            ['apjoker']         = { MadLib.JokerLists.Mult.Multiply },
            ['arsonist']        = { MadLib.JokerLists.Destructive.Card, MadLib.JokerLists.HandType['Full House'] },
            ['astral_bottle']   = { MadLib.JokerLists.Sell, MadLib.JokerLists.Effect.Card },
            ['big_cube']        = { MadLib.JokerLists.Chips.Multiply},
            ['biggestm']        = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.HandType['Pair'] },
            ['blacklist']       = { MadLib.JokerLists.Mult.Set, MadLib.JokerLists.Chips.Set },
            ['blender']         = { MadLib.JokerLists.Generative.Consumable },
            ['blurred']         = { MadLib.JokerLists.Stats.PlayHands },
            ['bonk']            = { MadLib.JokerLists.Chips.Add, MadLib.JokerLists.Scaling.Chips },
            ['bonkers']         = { MadLib.JokerLists.Mult.Add },
            ['bonusjoker']      = { MadLib.JokerLists.Probability, MadLib.JokerLists.Effect.Joker, MadLib.JokerLists.Effect.Game },
            ['booster']         = { MadLib.JokerLists.Effect.Game },
            ['boredom']         = { MadLib.JokerLists.Probability, MadLib.JokerLists.Retrigger.Joker, MadLib.JokerLists.Retrigger.Card },
            ['brittle']         = { MadLib.JokerLists.Effect.Card, MadLib.JokerLists.Food },
            ['bubblem']         = { MadLib.JokerLists.Generative.Joker, MadLib.JokerLists.HandType['Pair'] },
            ['busdriver']       = { MadLib.JokerLists.Mult.Add, MadLib.JokerLists.Probability },
            ['candy_basket']    = { MadLib.JokerLists.Sell, MadLib.JokerLists.Generative.Joker, MadLib.JokerLists.Scaling.Misc},
            ['candy_buttons']   = { MadLib.JokerLists.Effect.Game , MadLib.JokerLists.Food },
            ['candy_dagger']    = { MadLib.JokerLists.Destructive.Joker, MadLib.JokerLists.Generative.Joker },
            ['candy_sticks']    = { MadLib.JokerLists.Effect.Game },
            ['canvas']          = { MadLib.JokerLists.Retrigger.Joker },
            ['caramel']         = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.Food },
            ['chad']            = { MadLib.JokerLists.Retrigger.Joker },
            ['chili_pepper']    = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.Scaling.Mult, MadLib.JokerLists.Food },
            ['chocolate_dice']  = { MadLib.JokerLists.Probability, MadLib.JokerLists.Effect.Game },
            ['circulus_pistoris']   = { MadLib.JokerLists.Mult.Exponent, MadLib.JokerLists.Chips.Exponent },
            ['circus']          = { MadLib.JokerLists.Mult.Multiply },
            ['clash']           = { MadLib.JokerLists.Mult.Multiply },
            ['the']             = { MadLib.JokerLists.Mult.Multiply },
            ['clicked_cookie']  = { MadLib.JokerLists.Chips.Add, MadLib.JokerLists.Descaling },
            ['clockwork']       = { MadLib.JokerLists.Retrigger.Card, MadLib.JokerLists.Mult.multiply, MadLib.JokerLists.Scaling.Mult, MadLib.JokerLists.Effect.Card },
            ['CodeJoker']       = { MadLib.JokerLists.Generative.Consumable },
            ['compound_interest']   = { MadLib.JokerLists.Money.Add, MadLib.JokerLists.Scaling.Money },
            ['copypaste']       = { MadLib.JokerLists.Probability, MadLib.JokerLists.Generative.Consumable },
            ['cotton_candy']    = { MadLib.JokerLists.Sell, MadLib.JokerLists.Effect.Joker, MadLib.JokerLists.Food },
            ['crustulum']       = { MadLib.JokerLists.Chips.Add, MadLib.JokerLists.Scaling.Chips, MadLib.JokerLists.Effect.Game },
            ['cryptidmoment']   = { MadLib.JokerLists.Sell, MadLib.JokerLists.Effect.Joker },
            ['cube']            = { MadLib.JokerLists.Chips.Add },
            ['curse_sob']       = { MadLib.JokerLists.Generative.Joker},
            ['cut']             = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.Scaling.Mult, MadLib.JokerLists.Destructive.Consumable},
            ['delirious']       = { MadLib.JokerLists.Mult.Add, MadLib.JokerLists.HandType['Five of a Kind'] },
            ['demicolon']       = { MadLib.JokerLists.Effect.Joker },
            ['digitalhallucinations']   = { MadLib.JokerLists.Generative.Consumable, MadLib.JokerLists.Probability },
            ['discreet']        = { MadLib.JokerLists.Chips.Add, MadLib.JokerLists.HandType['Flush Five'] },
            ['doodlem']         = { MadLib.JokerLists.Generative.Consumable },
            ['Double Scale']    = { MadLib.JokerLists.Effect.Joker },
            ['dropshot']        = { MadLib.JokerLists.Mult.Add, MadLib.JokerLists.Scaling.Mult },
            ['dubious']         = { MadLib.JokerLists.Chips.Add, MadLib.JokerLists.HandType['High Card'] },
            ['duos']            = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.HandType['Two Pair'] },
            ['duplicare']       = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.Scaling.Mult },
            ['effarcire']       = { MadLib.JokerLists.Stats.HandSize },
            ['energia']         = { MadLib.JokerLists.Generative.Tag },
            ['equilib']         = { MadLib.JokerLists.Generative.Joker, MadLib.JokerLists.Meta },
            ['error']           = { MadLib.JokerLists.Meta },
            ['eternalflame']    = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.Scaling.Mult },
            ['exoplanet']       = { MadLib.JokerLists.Mult.Add },
            ['exponentia']      = { MadLib.JokerLists.Mult.Exponent, MadLib.JokerLists.Scaling.Mult },
            ['exposed']         = { MadLib.JokerLists.Retrigger.Card, MadLib.JokerLists.Effect.Card },
            ['eyeofhagane']     = { MadLib.JokerLists.RankType.Face, MadLib.JokerLists.Effect.Card },
            ['highfive']        = { MadLib.JokerLists.Rank['5'], MadLib.JokerLists.Effect.Card },
            ['facile']          = { MadLib.JokerLists.Mult.Exponent },
            ['familiar_currency']   = { MadLib.JokerLists.Generative.Joker },
            ['filler']          = { MadLib.JokerLists.HandType['High Card'], MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.Meta }, -- meta because it requires manip to use
            ['fractal_fingers'] = { MadLib.JokerLists.Effect.Game },
            ['flip_side']       = { MadLib.JokerLists.Retrigger.Joker },
            ['foodm']           = { MadLib.JokerLists.Mult.Add, MadLib.JokerLists.Food },
            ['foolhardy']       = { MadLib.JokerLists.Mult.Add },
            ['undefined']       = { MadLib.JokerLists.Mult.Add },
            ['formidiulosus']   = { MadLib.JokerLists.Generative.Joker, MadLib.JokerLists.Mult.Exponent, MadLib.JokerLists.Scaling.Mult },
            ['foxy']            = { MadLib.JokerLists.Mult.Add, MadLib.JokerLists.HandType['Full House'] },
            ['fspinner']        = { MadLib.JokerLists.Chips.Add, MadLib.JokerLists.Scaling.Chips },
            ['fuckedup']        = { MadLib.JokerLists.Mult.Add },
            ['gardenfork']      = { MadLib.JokerLists.Money.Add, MadLib.JokerLists.Rank['Ace'], MadLib.JokerLists.Rank['7'] },
            ['gemino']          = { MadLib.JokerLists.Effect.Joker },
            ['giggly']          = { MadLib.JokerLists.Mult.Add, MadLib.JokerLists.HandType['High Card'] },
            ['goldjoker']       = { MadLib.JokerLists.Money.Add, MadLib.JokerLists.Scaling.Money },
            ['googol_play']     = { MadLib.JokerLists.Probability, MadLib.JokerLists.Mult.Multiply },
            ['happy']           = { MadLib.JokerLists.Mult.Exponent },
            ['home']            = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.HandType['Full House'] },
            ['hunger']          = { MadLib.JokerLists.Money.Add },
            ['hunting_season']  = { MadLib.JokerLists.Destructive.Card },
            ['iterum']          = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.Retrigger.Card },
            ['jawbreaker']      = { MadLib.JokerLists.Effect.Card, MadLib.JokerLists.Food },
            ['jimball']         = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.Scaling.Mult },
            ['jollysus']        = { MadLib.JokerLists.Generative.Joker },
            ['jtron']           = { MadLib.JokerLists.Mult.Exponent },
            ['kidnap']          = { MadLib.JokerLists.Money.Add, MadLib.JokerLists.Scaling.Money },
            ['kittyprinter']    = { MadLib.JokerLists.Mult.Multiply },
            ['kooky']           = { MadLib.JokerLists.Mult.Add, MadLib.JokerLists.HandType['Flush Five'] },
            ['krustytheclown']  = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.Scaling.Mult },
            ['kscope']          = { MadLib.JokerLists.Effect.Joker },
            ['lebaron_james']   = { MadLib.JokerLists.Stats.HandSize, MadLib.JokerLists.Retrigger.Card, MadLib.JokerLists.Rank['King'] },
            ['lightupthenight'] = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.Rank['7'], MadLib.JokerLists.Rank['2'] },
            ['loopy']           = { MadLib.JokerLists.Retrigger.Joker, MadLib.JokerLists.Scaling.Misc },
            ['lucky_joker']     = { MadLib.JokerLists.Money.Add },
            ['m']               = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.Scaling.Mult },
            ['M']               = { MadLib.JokerLists.Generative.Joker },
            ['macabre']         = { MadLib.JokerLists.Destructive.Joker, MadLib.JokerLists.Generative.Joker },
            ['magnet']          = { MadLib.JokerLists.Money.Add },
            ['manic']           = { MadLib.JokerLists.Mult.Add, MadLib.JokerLists.HandType['Straight Flush'] },
            ['mask']            = { MadLib.JokerLists.Retrigger.Card, MadLib.JokerLists.RankType.Face, MadLib.JokerLists.Effect.Card},
            ['maximized']       = { MadLib.JokerLists.RankType.Face, MadLib.JokerLists.Rank['King'], MadLib.JokerLists.Number, MadLib.JokerLists.Rank['10'] },
            ['maze']            = { MadLib.JokerLists.Effect.Game },
            ['megg']            = { MadLib.JokerLists.Generative.Joker, MadLib.JokerLists.Scaling.Misc },
            ['mellowcreme']     = { MadLib.JokerLists.Sell, MadLib.JokerLists.Effect.Joker },
            ['membershipcard']  = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.Meta},
            ['membershipcardtwo']   = { MadLib.JokerLists.Chips.Add, MadLib.JokerLists.Meta },
            ['meteor']          = { MadLib.JokerLists.Chips.Add },
            ['mneon']           = { MadLib.JokerLists.Money.Add },
            ['mondrian']        = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.Scaling.Mult },
            ['monkey_dagger']   = { MadLib.JokerLists.Chips.Multiply, MadLib.JokerLists.Scaling.Chips, MadLib.JokerLists.Destructive.Joker },
            ['monopoly_money']  = { MadLib.JokerLists.Probability, MadLib.JokerLists.Destructive.Joker, MadLib.JokerLists.Money.Multiply },
            ['morse']           = { MadLib.JokerLists.Money.Add, MadLib.JokerLists.Scaling.Money },
            ['mprime']          = { MadLib.JokerLists.Generative.Joker, MadLib.JokerLists.Scaling.Misc },
            ['mstack']          = { MadLib.JokerLists.Retrigger.Card, MadLib.JokerLists.Scaling.Misc },
            ['multjoker']       = { MadLib.JokerLists.Probability, MadLib.JokerLists.Generative.Consumable },
            ['necromancer']     = { MadLib.JokerLists.Generative.Card },
            ['negative']        = { MadLib.JokerLists.Stats.JokerSlots },
            ['nice']            = { MadLib.JokerLists.Chips.Add, MadLib.JokerLists.Rank['6'], MadLib.JokerLists.Rank['9'] },
            ['night']           = { MadLib.JokerLists.Mult.Exponent },
            ['nosound']         = { MadLib.JokerLists.Retrigger.Card, MadLib.JokerLists.Rank['7'] },
            ['notebook']        = { MadLib.JokerLists.Probability, MadLib.JokerLists.Stats.JokerSlots },
            ['number_blocks']   = { MadLib.JokerLists.Money.Add, MadLib.JokerLists.Scaling.Money, MadLib.JokerLists.RankType.Random },
            ['nuts']            = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.HandType['Straight Flush'] },
            ['nutty']           = { MadLib.JokerLists.Mult.Add, MadLib.JokerLists.HandType['Four of a Kind'] },
            ['oil_lamp']        = { MadLib.JokerLists.Effect.Joker, MadLib.JokerLists.Meta },
            ['old_blueprint']   = { MadLib.JokerLists.Retrigger.Joker, MadLib.JokerLists.Probability },
            ['oldcandy']        = { MadLib.JokerLists.Sell, MadLib.JokerLists.Stats.HandSize, MadLib.JokerLists.Food },
            ['oldinvisible']    = { MadLib.JokerLists.Generative.Joker },
            ['panopticon']      = { MadLib.JokerLists.Effect.Game },
            ['penetrating']     = { MadLib.JokerLists.Chips.Add },
            ['pickle']          = { MadLib.JokerLists.Generative.Tag, MadLib.JokerLists.Descaling, MadLib.JokerLists.Food },
            ['pirate_dagger']   = { MadLib.JokerLists.Destructive.Joker, MadLib.JokerLists.Chips.Multiply, MadLib.JokerLists.Scaling.Chips },
            ['pity_prize']      = { MadLib.JokerLists.Generative.Tag },
            ['pot_of_jokes']    = { MadLib.JokerLists.Stats.HandSize, MadLib.JokerLists.Scaling.Misc },
            ['primus']          = { MadLib.JokerLists.Mult.Exponent, MadLib.JokerLists.Scaling.Mult },
            ['python']          = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.Scaling.Mult },
            ['quintet']         = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.HandType['Five of a Kind'] },
            ['redbloon']        = { MadLib.JokerLists.Money.Add },
            ['redeo']           = { MadLib.JokerLists.Effect.Game },
            ['reverse']         = { MadLib.JokerLists.Generative.Joker },
            ['rnjoker']         = {}, -- random as fuck
            ['sacrifice']       = { MadLib.JokerLists.Generative.Joker },
            ['sapling']         = { MadLib.JokerLists.Sell, MadLib.JokerLists.Generative.Joker },
            ['savvy']           = { MadLib.JokerLists.Chips.Add, MadLib.JokerLists.HandType['Five of a Kind'] },
            ['scalae']          = { MadLib.JokerLists.Effect.Joker },
            ['scrabble']        = { MadLib.JokerLists.Probability, MadLib.JokerLists.Generative.Joker},
            ['seal_the_deal']   = { MadLib.JokerLists.Effect.Card },
            ['shrewd']          = { MadLib.JokerLists.Chips.Add, MadLib.JokerLists.HandType['Four of a Kind'] },
            ['silly']           = { MadLib.JokerLists.Mult.Add, MadLib.JokerLists.HandType['Full House'] },
            ['smallestm']       = { MadLib.JokerLists.Generative.Tag, MadLib.JokerLists.HandType['Pair'] },
            ['soccer']          = { MadLib.JokerLists.Stats.HandSize, MadLib.JokerLists.Stats.JokerSlots, MadLib.JokerLists.Effect.Game }, -- TODO: add more?
            ['subtle']          = { MadLib.JokerLists.Chips.Add, MadLib.JokerLists.HandType['Flush House']},
            ['fleshpanopticon'] = { MadLib.JokerLists.Generative.Joker },
            ['sock_and_sock']   = { MadLib.JokerLists.Retrigger.Card },
            ['brokenhome']      = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.Probability },
            ['yarnball']        = { MadLib.JokerLists.Effect.Game, MadLib.JokerLists.Meta },
            ['spaceglobe']      = { MadLib.JokerLists.Chips.Multiply, MadLib.JokerLists.Scaling.Chips },
            ['spectogram']      = { MadLib.JokerLists.Retrigger.Joker },
            ['speculo']         = { MadLib.JokerLists.Generative.Joker },
            ['stardust']        = { MadLib.JokerLists.Mult.Multiply },
            ['stella_mortis']   = { MadLib.JokerLists.Destructive.Consumable, MadLib.JokerLists.Mult.Exponent, MadLib.JokerLists.Scaling.Mult },
            ['stronghold']      = { MadLib.JokerLists.Mult.Add },
            ['supercell']       = { MadLib.JokerLists.Chips.Add, MadLib.JokerLists.Mult.Add, MadLib.JokerLists.Chips.Multiply, MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.Money.Add },
            ['sus']             = { MadLib.JokerLists.Generative.Card, MadLib.JokerLists.Destructive.Card, MadLib.JokerLists.Rank['King'], MadLib.JokerLists.Suit['Hearts'] },
            ['swarm']           = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.HandType['Flush Five'] },
            ['sync_catalyst']   = { MadLib.JokerLists.Effect.Game },
            ['tax_fraud']       = { MadLib.JokerLists.Money.Add },
            ['tenebris']        = { MadLib.JokerLists.Money.Add, MadLib.JokerLists.Stats.JokerSlots },
            ['translucent']     = { MadLib.JokerLists.Sell, MadLib.JokerLists.Generative.Joker },
            ['treacherous']     = { MadLib.JokerLists.Chips.Add },
            ['nebulous']        = { MadLib.JokerLists.Chips.Add },
            ['words_cant_even'] = { MadLib.JokerLists.Mult.Multiply },
            ['many_lost_minds'] = { MadLib.JokerLists.Chips.Add },
            ['annihalation']    = { MadLib.JokerLists.Mult.Multiply },
            ['trick_or_treat']  = { MadLib.JokerLists.Sell, MadLib.JokerLists.Generative.Joker },
            ['tricksy']         = { MadLib.JokerLists.Chips.Add, MadLib.JokerLists.HandType['Straight Flush'] },
            ['triplet_rhythm']  = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.Rank['3'] },
            ['tropical_smoothie']   = { MadLib.JokerLists.Effect.Joker, MadLib.JokerLists.Meta, MadLib.JokerLists.Sell, MadLib.JokerLists.Food },
            ['unity']           = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.HandType['Flush House'] },
            ['universe']        = { MadLib.JokerLists.Mult.Exponent },
            ['universum']       = { MadLib.JokerLists.Effect.Game },
            ['unjust_dagger']    = { MadLib.JokerLists.Destructive.Joker, MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.Scaling.Mult },
            ['virgo']           = { MadLib.JokerLists.Scaling.Money, MadLib.JokerLists.Sell, MadLib.JokerLists.Generative.Joker, MadLib.JokerLists.HandType['Pair'] },
            ['wacky']           = { MadLib.JokerLists.Mult.Add, MadLib.JokerLists.HandType['Flush House'] },
            ['waluigi']         = { MadLib.JokerLists.Mult.Multiply },
            ['wario']           = { MadLib.JokerLists.Money.Add },
            ['wee_fib']         = { MadLib.JokerLists.Mult.Add, MadLib.JokerLists.Scaling.Mult },
            ['wee_gaming']      = { MadLib.JokerLists.Retrigger.Card, MadLib.JokerLists.Rank['2'] },
            ['wheelhope']       = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.Scaling.Mult },
            ['whip']            = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.Scaling.Mult, MadLib.JokerLists.Rank['7'] },
            ['wonka_bar']       = { MadLib.JokerLists.Sell, MadLib.JokerLists.Effect.Game },
            ['wrapped']         = { MadLib.JokerLists.Generative.Joker, MadLib.JokerLists.Food },
            ['wtf']             = { MadLib.JokerLists.Mult.Multiply },
            ['zooble']          = { MadLib.JokerLists.Mult.Add, MadLib.JokerLists.Scaling.Mult, MadLib.JokerLists.HandType['Straight'] },
            ['queens_gambit']   = { MadLib.JokerLists.Rank['Queen'], MadLib.JokerLists.HandType['Straight Flush'], MadLib.JokerLists.Destructive.Card, MadLib.JokerLists.Generative.Joker },
            ['cursor']          = { MadLib.JokerLists.Chips.Add, MadLib.JokerLists.Scaling.Chips },
            ['longboi']         = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.Scaling.Mult, MadLib.JokerLists.Meta },
        },
        PointValues = {
            Editions = {
                ['glitched']        = 10,
                ['mosaic']          = 9,
                ['oversaturated']   = 12,
                ['fragile']         = 11,
                ['golden']          = 8,
                ['blurred']         = 7,
                ['noisy']           = 9,
                ['astral']          = 15,
                ['jolly']           = 16,
                ['double_sided']    = 10,
            },
            Enhancements = {
                ['echo']        = 10,
                ['light']       = 8,
                ['abstract'] 	= 12,
            },
        },
        RarityValues = {

        },
        StickerLists = {
            ['pinned'] = { MadLib.StickerLists.Bad },
            ['banana'] = { MadLib.StickerLists.Bad, MadLib.StickerLists.Destructive }
        },
        Weights = {
            Boosters = {
                ['meme_1']          = 4,
                ['meme_two']        = 2,
                ['meme_three'] 	    = 1,
                ['code_normal_1']   = 4,
                ['code_jumbo_1']    = 2,
                ['code_mega_1']     = 1,
                ['empowered']       = 0.3,
                ['baneful_1']       = 0.5,
            },
            Editions = { -- idk for these
                ['glitched']        = 0.5,
                ['mosaic']          = 0.8,
                ['oversaturated']   = 0.5,
                ['fragile']         = 0.5,
                ['golden']          = 0.5,
                ['blurred']         = 0.4,
                ['noisy']           = 0.4,
                ['astral']          = 0.2,
                ['jolly']           = 0.8,
                ['double_sided']    = 0.4,
            },
            Enhancements = {
                ['echo']        = 2,
                ['light']       = 2,
                ['abstract'] 	= 0.4,
            }
        },
    },
    init = function(c)
        -- Prefix
        local p = c.prefix..'_'

        -- transfers custom hand types - spectrum depends on mods added (goes by madlib's spectrum priority)
        local Bulwark       = p..'Bulwark'
        local Cluster       = p..'Clusterfuck'
        local UltimatePair  = p..'UltPair'
        local WholeDeck     = p..'WholeDeck'
        local None          = p..'None'

        local joker_poker_hands = {
            ['adroit']              = { Bulwark },
            ['bonkers']             = { Bulwark },
            ['stronghold']          = { Bulwark },
            ['fuckedup']            = { Cluster },
            ['penetrating']         = { Cluster },
            ['wtf']                 = { Cluster },
            ['foolhardy']           = { UltimatePair },
            ['treacherous']         = { UltimatePair },
            ['clash']               = { UltimatePair },
            ['words_cant_even']     = { WholeDeck },
            ['many_lost_minds']     = { WholeDeck },
            ['annihalation']        = { WholeDeck },
            ['undefined']           = { None },
            ['nebulous']            = { None },
            ['the']                 = { None },
        }

        MadLib.loop_table_func(joker_poker_hands, function(k,v) table.insert(c.JokerCategories[k], MadLib.JokerLists.HandType[v]) end)

        local joker_ranks = {
            ['wee_fib']             = { 'Ace', '2', '3', '5', '8'},
            ['primus']              = { 'Ace', '2', '3', '5', '7'},
        }
        MadLib.transfer_to_new_table(joker_ranks,c.content.JokerRanks)

        -- Meme category for Meme Jokers
        MadLib.JokerLists.Meme = {
            'j_jolly',
            'j_mr_bones',
            'j_space',
            'j_obelisk',
        }
        local cryptid_memes = {
            'm',
            'happy',
            'jimball',
            'cube',
            'krustytheclown',
            'boredom',
            'blurred',
            'chad',
            'sus',
            'curse_sob',
            'nice',
            'filler',
            'bonk',
            'reverse',
            'waluigi',
        }
        MadLib.loop_func(cryptid_memes, function(v) table.insert(MadLib.JokerLists.Meme, 'j_cry_'..v) end)

        -- Meme category for M/Jolly Jokers
        MadLib.JokerLists.M = {
            'j_jolly'
        }
        local cryptid_ms = {
            'bubblem',
            'bonk',
            'doodlem',
            'foodm',
            'biggestm',
            'jollysus',
            'loopy',
            'm',
            'M',
            'mstack',
            'macabre',
            'megg',
            'longboi',
            'notebook',
            'mneon',
            'reverse',
            'sacrifice',
            'scrabble',
            'smallestm',
            'mprime',
            'virgo'
        }
        MadLib.loop_func(cryptid_ms, function(v) table.insert(MadLib.JokerLists.M, 'j_cry_'..v) end)

		return true
    end,
}
