return {
    modid   = 'Cryptid',
    prefix  = 'cry',
    content = {
        BanLists = {
            ['SuperBlinds'] = {
                'bl_cry_final_orb'
            },
            ['OPBlinds'] = {
                'bl_cry_clock',
                'bl_cry_joke',
                'bl_cry_tax',
                'bl_cry_final_loop',
                'bl_cry_final_orb'
            },
        },
        JokerRanks = { },
        JokerSuits = { },
        JokerCategories = { -- sorted alphabetically because fuck
            ['j_cry_adroit']          = { MadLib.JokerLists.Chips.Add },
            ['j_cry_altgoogl']        = { MadLib.JokerLists.Sell, MadLib.JokerLists.Generative.Jokers },
            ['j_cry_antennastoheaven']    = { MadLib.JokerLists.Sell, MadLib.JokerLists.Generative.Jokers },
            ['j_cry_apjoker']         = { MadLib.JokerLists.Mult.Multiply },
            ['j_cry_arsonist']        = { MadLib.JokerLists.Destructive.Card, MadLib.JokerLists.HandType['j_cry_Full House'] },
            ['j_cry_astral_bottle']   = { MadLib.JokerLists.Sell, MadLib.JokerLists.Effect.Card },
            ['j_cry_big_cube']        = { MadLib.JokerLists.Chips.Multiply},
            ['j_cry_biggestm']        = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.HandType['j_cry_Pair'] },
            ['j_cry_blacklist']       = { MadLib.JokerLists.Mult.Set, MadLib.JokerLists.Chips.Set },
            ['j_cry_blender']         = { MadLib.JokerLists.Generative.Consumable },
            ['j_cry_blurred']         = { MadLib.JokerLists.Stats.PlayHands },
            ['j_cry_bonk']            = { MadLib.JokerLists.Chips.Add, MadLib.JokerLists.Scaling.Chips },
            ['j_cry_bonkers']         = { MadLib.JokerLists.Mult.Add },
            ['j_cry_bonusjoker']      = { MadLib.JokerLists.Probability, MadLib.JokerLists.Effect.Joker, MadLib.JokerLists.Effect.Game },
            ['j_cry_booster']         = { MadLib.JokerLists.Effect.Game },
            ['j_cry_boredom']         = { MadLib.JokerLists.Probability, MadLib.JokerLists.Retrigger.Joker, MadLib.JokerLists.Retrigger.Card },
            ['j_cry_brittle']         = { MadLib.JokerLists.Effect.Card, MadLib.JokerLists.Food },
            ['j_cry_bubblem']         = { MadLib.JokerLists.Generative.Joker, MadLib.JokerLists.HandType['j_cry_Pair'] },
            ['j_cry_busdriver']       = { MadLib.JokerLists.Mult.Add, MadLib.JokerLists.Probability },
            ['j_cry_candy_basket']    = { MadLib.JokerLists.Sell, MadLib.JokerLists.Generative.Joker, MadLib.JokerLists.Scaling.Misc},
            ['j_cry_candy_buttons']   = { MadLib.JokerLists.Effect.Game , MadLib.JokerLists.Food },
            ['j_cry_candy_dagger']    = { MadLib.JokerLists.Destructive.Joker, MadLib.JokerLists.Generative.Joker },
            ['j_cry_candy_sticks']    = { MadLib.JokerLists.Effect.Game },
            ['j_cry_canvas']          = { MadLib.JokerLists.Retrigger.Joker },
            ['j_cry_caramel']         = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.Food },
            ['j_cry_chad']            = { MadLib.JokerLists.Retrigger.Joker },
            ['j_cry_chili_pepper']    = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.Scaling.Mult, MadLib.JokerLists.Food },
            ['j_cry_chocolate_dice']  = { MadLib.JokerLists.Probability, MadLib.JokerLists.Effect.Game },
            ['j_cry_circulus_pistoris']   = { MadLib.JokerLists.Mult.Exponent, MadLib.JokerLists.Chips.Exponent },
            ['j_cry_circus']          = { MadLib.JokerLists.Mult.Multiply },
            ['j_cry_clash']           = { MadLib.JokerLists.Mult.Multiply },
            ['j_cry_the']             = { MadLib.JokerLists.Mult.Multiply },
            ['j_cry_clicked_cookie']  = { MadLib.JokerLists.Chips.Add, MadLib.JokerLists.Descaling },
            ['j_cry_clockwork']       = { MadLib.JokerLists.Retrigger.Card, MadLib.JokerLists.Mult.multiply, MadLib.JokerLists.Scaling.Mult, MadLib.JokerLists.Effect.Card },
            ['j_cry_CodeJoker']       = { MadLib.JokerLists.Generative.Consumable },
            ['j_cry_compound_interest']   = { MadLib.JokerLists.Money.Add, MadLib.JokerLists.Scaling.Money },
            ['j_cry_copypaste']       = { MadLib.JokerLists.Probability, MadLib.JokerLists.Generative.Consumable },
            ['j_cry_cotton_candy']    = { MadLib.JokerLists.Sell, MadLib.JokerLists.Effect.Joker, MadLib.JokerLists.Food },
            ['j_cry_crustulum']       = { MadLib.JokerLists.Chips.Add, MadLib.JokerLists.Scaling.Chips, MadLib.JokerLists.Effect.Game },
            ['j_cry_cryptidmoment']   = { MadLib.JokerLists.Sell, MadLib.JokerLists.Effect.Joker },
            ['j_cry_cube']            = { MadLib.JokerLists.Chips.Add },
            ['j_cry_curse_sob']       = { MadLib.JokerLists.Generative.Joker},
            ['j_cry_cut']             = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.Scaling.Mult, MadLib.JokerLists.Destructive.Consumable},
            ['j_cry_delirious']       = { MadLib.JokerLists.Mult.Add, MadLib.JokerLists.HandType['j_cry_Five of a Kind'] },
            ['j_cry_demicolon']       = { MadLib.JokerLists.Effect.Joker },
            ['j_cry_digitalhallucinations']   = { MadLib.JokerLists.Generative.Consumable, MadLib.JokerLists.Probability },
            ['j_cry_discreet']        = { MadLib.JokerLists.Chips.Add, MadLib.JokerLists.HandType['j_cry_Flush Five'] },
            ['j_cry_doodlem']         = { MadLib.JokerLists.Generative.Consumable },
            ['j_cry_Double Scale']    = { MadLib.JokerLists.Effect.Joker },
            ['j_cry_dropshot']        = { MadLib.JokerLists.Mult.Add, MadLib.JokerLists.Scaling.Mult },
            ['j_cry_dubious']         = { MadLib.JokerLists.Chips.Add, MadLib.JokerLists.HandType['j_cry_High Card'] },
            ['j_cry_duos']            = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.HandType['j_cry_Two Pair'] },
            ['j_cry_duplicare']       = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.Scaling.Mult },
            ['j_cry_effarcire']       = { MadLib.JokerLists.Stats.HandSize },
            ['j_cry_energia']         = { MadLib.JokerLists.Generative.Tag },
            ['j_cry_equilib']         = { MadLib.JokerLists.Generative.Joker, MadLib.JokerLists.Meta },
            ['j_cry_error']           = { MadLib.JokerLists.Meta },
            ['j_cry_eternalflame']    = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.Scaling.Mult },
            ['j_cry_exoplanet']       = { MadLib.JokerLists.Mult.Add },
            ['j_cry_exponentia']      = { MadLib.JokerLists.Mult.Exponent, MadLib.JokerLists.Scaling.Mult },
            ['j_cry_exposed']         = { MadLib.JokerLists.Retrigger.Card, MadLib.JokerLists.Effect.Card },
            ['j_cry_eyeofhagane']     = { MadLib.JokerLists.RankType.Face, MadLib.JokerLists.Effect.Card },
            ['j_cry_highfive']        = { MadLib.JokerLists.Rank['j_cry_5'], MadLib.JokerLists.Effect.Card },
            ['j_cry_facile']          = { MadLib.JokerLists.Mult.Exponent },
            ['j_cry_familiar_currency']   = { MadLib.JokerLists.Generative.Joker },
            ['j_cry_filler']          = { MadLib.JokerLists.HandType['j_cry_High Card'], MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.Meta }, -- meta because it requires manip to use
            ['j_cry_fractal_fingers'] = { MadLib.JokerLists.Effect.Game },
            ['j_cry_flip_side']       = { MadLib.JokerLists.Retrigger.Joker },
            ['j_cry_foodm']           = { MadLib.JokerLists.Mult.Add, MadLib.JokerLists.Food },
            ['j_cry_foolhardy']       = { MadLib.JokerLists.Mult.Add },
            ['j_cry_undefined']       = { MadLib.JokerLists.Mult.Add },
            ['j_cry_formidiulosus']   = { MadLib.JokerLists.Generative.Joker, MadLib.JokerLists.Mult.Exponent, MadLib.JokerLists.Scaling.Mult },
            ['j_cry_foxy']            = { MadLib.JokerLists.Mult.Add, MadLib.JokerLists.HandType['j_cry_Full House'] },
            ['j_cry_fspinner']        = { MadLib.JokerLists.Chips.Add, MadLib.JokerLists.Scaling.Chips },
            ['j_cry_fuckedup']        = { MadLib.JokerLists.Mult.Add },
            ['j_cry_gardenfork']      = { MadLib.JokerLists.Money.Add, MadLib.JokerLists.Rank['j_cry_Ace'], MadLib.JokerLists.Rank['j_cry_7'] },
            ['j_cry_gemino']          = { MadLib.JokerLists.Effect.Joker },
            ['j_cry_giggly']          = { MadLib.JokerLists.Mult.Add, MadLib.JokerLists.HandType['j_cry_High Card'] },
            ['j_cry_goldjoker']       = { MadLib.JokerLists.Money.Add, MadLib.JokerLists.Scaling.Money },
            ['j_cry_googol_play']     = { MadLib.JokerLists.Probability, MadLib.JokerLists.Mult.Multiply },
            ['j_cry_happy']           = { MadLib.JokerLists.Mult.Exponent },
            ['j_cry_home']            = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.HandType['j_cry_Full House'] },
            ['j_cry_hunger']          = { MadLib.JokerLists.Money.Add },
            ['j_cry_hunting_season']  = { MadLib.JokerLists.Destructive.Card },
            ['j_cry_iterum']          = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.Retrigger.Card },
            ['j_cry_jawbreaker']      = { MadLib.JokerLists.Effect.Card, MadLib.JokerLists.Food },
            ['j_cry_jimball']         = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.Scaling.Mult },
            ['j_cry_jollysus']        = { MadLib.JokerLists.Generative.Joker },
            ['j_cry_jtron']           = { MadLib.JokerLists.Mult.Exponent },
            ['j_cry_kidnap']          = { MadLib.JokerLists.Money.Add, MadLib.JokerLists.Scaling.Money },
            ['j_cry_kittyprinter']    = { MadLib.JokerLists.Mult.Multiply },
            ['j_cry_kooky']           = { MadLib.JokerLists.Mult.Add, MadLib.JokerLists.HandType['j_cry_Flush Five'] },
            ['j_cry_krustytheclown']  = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.Scaling.Mult },
            ['j_cry_kscope']          = { MadLib.JokerLists.Effect.Joker },
            ['j_cry_lebaron_james']   = { MadLib.JokerLists.Stats.HandSize, MadLib.JokerLists.Retrigger.Card, MadLib.JokerLists.Rank['j_cry_King'] },
            ['j_cry_lightupthenight'] = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.Rank['j_cry_7'], MadLib.JokerLists.Rank['j_cry_2'] },
            ['j_cry_loopy']           = { MadLib.JokerLists.Retrigger.Joker, MadLib.JokerLists.Scaling.Misc },
            ['j_cry_lucky_joker']     = { MadLib.JokerLists.Money.Add },
            ['j_cry_m']               = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.Scaling.Mult },
            ['j_cry_M']               = { MadLib.JokerLists.Generative.Joker },
            ['j_cry_macabre']         = { MadLib.JokerLists.Destructive.Joker, MadLib.JokerLists.Generative.Joker },
            ['j_cry_magnet']          = { MadLib.JokerLists.Money.Add },
            ['j_cry_manic']           = { MadLib.JokerLists.Mult.Add, MadLib.JokerLists.HandType['j_cry_Straight Flush'] },
            ['j_cry_mask']            = { MadLib.JokerLists.Retrigger.Card, MadLib.JokerLists.RankType.Face, MadLib.JokerLists.Effect.Card},
            ['j_cry_maximized']       = { MadLib.JokerLists.RankType.Face, MadLib.JokerLists.Rank['j_cry_King'], MadLib.JokerLists.Number, MadLib.JokerLists.Rank['j_cry_10'] },
            ['j_cry_maze']            = { MadLib.JokerLists.Effect.Game },
            ['j_cry_megg']            = { MadLib.JokerLists.Generative.Joker, MadLib.JokerLists.Scaling.Misc },
            ['j_cry_mellowcreme']     = { MadLib.JokerLists.Sell, MadLib.JokerLists.Effect.Joker },
            ['j_cry_membershipcard']  = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.Meta},
            ['j_cry_membershipcardtwo']   = { MadLib.JokerLists.Chips.Add, MadLib.JokerLists.Meta },
            ['j_cry_meteor']          = { MadLib.JokerLists.Chips.Add },
            ['j_cry_mneon']           = { MadLib.JokerLists.Money.Add },
            ['j_cry_mondrian']        = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.Scaling.Mult },
            ['j_cry_monkey_dagger']   = { MadLib.JokerLists.Chips.Multiply, MadLib.JokerLists.Scaling.Chips, MadLib.JokerLists.Destructive.Joker },
            ['j_cry_monopoly_money']  = { MadLib.JokerLists.Probability, MadLib.JokerLists.Destructive.Joker, MadLib.JokerLists.Money.Multiply },
            ['j_cry_morse']           = { MadLib.JokerLists.Money.Add, MadLib.JokerLists.Scaling.Money },
            ['j_cry_mprime']          = { MadLib.JokerLists.Generative.Joker, MadLib.JokerLists.Scaling.Misc },
            ['j_cry_mstack']          = { MadLib.JokerLists.Retrigger.Card, MadLib.JokerLists.Scaling.Misc },
            ['j_cry_multjoker']       = { MadLib.JokerLists.Probability, MadLib.JokerLists.Generative.Consumable },
            ['j_cry_necromancer']     = { MadLib.JokerLists.Generative.Card },
            ['j_cry_negative']        = { MadLib.JokerLists.Stats.JokerSlots },
            ['j_cry_nice']            = { MadLib.JokerLists.Chips.Add, MadLib.JokerLists.Rank['j_cry_6'], MadLib.JokerLists.Rank['j_cry_9'] },
            ['j_cry_night']           = { MadLib.JokerLists.Mult.Exponent },
            ['j_cry_nosound']         = { MadLib.JokerLists.Retrigger.Card, MadLib.JokerLists.Rank['j_cry_7'] },
            ['j_cry_notebook']        = { MadLib.JokerLists.Probability, MadLib.JokerLists.Stats.JokerSlots },
            ['j_cry_number_blocks']   = { MadLib.JokerLists.Money.Add, MadLib.JokerLists.Scaling.Money, MadLib.JokerLists.RankType.Random },
            ['j_cry_nuts']            = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.HandType['j_cry_Straight Flush'] },
            ['j_cry_nutty']           = { MadLib.JokerLists.Mult.Add, MadLib.JokerLists.HandType['j_cry_Four of a Kind'] },
            ['j_cry_oil_lamp']        = { MadLib.JokerLists.Effect.Joker, MadLib.JokerLists.Meta },
            ['j_cry_old_blueprint']   = { MadLib.JokerLists.Retrigger.Joker, MadLib.JokerLists.Probability },
            ['j_cry_oldcandy']        = { MadLib.JokerLists.Sell, MadLib.JokerLists.Stats.HandSize, MadLib.JokerLists.Food },
            ['j_cry_oldinvisible']    = { MadLib.JokerLists.Generative.Joker },
            ['j_cry_panopticon']      = { MadLib.JokerLists.Effect.Game },
            ['j_cry_penetrating']     = { MadLib.JokerLists.Chips.Add },
            ['j_cry_pickle']          = { MadLib.JokerLists.Generative.Tag, MadLib.JokerLists.Descaling, MadLib.JokerLists.Food },
            ['j_cry_pirate_dagger']   = { MadLib.JokerLists.Destructive.Joker, MadLib.JokerLists.Chips.Multiply, MadLib.JokerLists.Scaling.Chips },
            ['j_cry_pity_prize']      = { MadLib.JokerLists.Generative.Tag },
            ['j_cry_pot_of_jokes']    = { MadLib.JokerLists.Stats.HandSize, MadLib.JokerLists.Scaling.Misc },
            ['j_cry_primus']          = { MadLib.JokerLists.Mult.Exponent, MadLib.JokerLists.Scaling.Mult },
            ['j_cry_python']          = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.Scaling.Mult },
            ['j_cry_quintet']         = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.HandType['j_cry_Five of a Kind'] },
            ['j_cry_redbloon']        = { MadLib.JokerLists.Money.Add },
            ['j_cry_redeo']           = { MadLib.JokerLists.Effect.Game },
            ['j_cry_reverse']         = { MadLib.JokerLists.Generative.Joker },
            ['j_cry_rnjoker']         = {}, -- random as fuck
            ['j_cry_sacrifice']       = { MadLib.JokerLists.Generative.Joker },
            ['j_cry_sapling']         = { MadLib.JokerLists.Sell, MadLib.JokerLists.Generative.Joker },
            ['j_cry_savvy']           = { MadLib.JokerLists.Chips.Add, MadLib.JokerLists.HandType['j_cry_Five of a Kind'] },
            ['j_cry_scalae']          = { MadLib.JokerLists.Effect.Joker },
            ['j_cry_scrabble']        = { MadLib.JokerLists.Probability, MadLib.JokerLists.Generative.Joker},
            ['j_cry_seal_the_deal']   = { MadLib.JokerLists.Effect.Card },
            ['j_cry_shrewd']          = { MadLib.JokerLists.Chips.Add, MadLib.JokerLists.HandType['j_cry_Four of a Kind'] },
            ['j_cry_silly']           = { MadLib.JokerLists.Mult.Add, MadLib.JokerLists.HandType['j_cry_Full House'] },
            ['j_cry_smallestm']       = { MadLib.JokerLists.Generative.Tag, MadLib.JokerLists.HandType['j_cry_Pair'] },
            ['j_cry_soccer']          = { MadLib.JokerLists.Stats.HandSize, MadLib.JokerLists.Stats.JokerSlots, MadLib.JokerLists.Effect.Game }, -- TODO: add more?
            ['j_cry_subtle']          = { MadLib.JokerLists.Chips.Add, MadLib.JokerLists.HandType['j_cry_Flush House']},
            ['j_cry_fleshpanopticon'] = { MadLib.JokerLists.Generative.Joker },
            ['j_cry_sock_and_sock']   = { MadLib.JokerLists.Retrigger.Card },
            ['j_cry_brokenhome']      = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.Probability },
            ['j_cry_yarnball']        = { MadLib.JokerLists.Effect.Game, MadLib.JokerLists.Meta },
            ['j_cry_spaceglobe']      = { MadLib.JokerLists.Chips.Multiply, MadLib.JokerLists.Scaling.Chips },
            ['j_cry_spectogram']      = { MadLib.JokerLists.Retrigger.Joker },
            ['j_cry_speculo']         = { MadLib.JokerLists.Generative.Joker },
            ['j_cry_stardust']        = { MadLib.JokerLists.Mult.Multiply },
            ['j_cry_stella_mortis']   = { MadLib.JokerLists.Destructive.Consumable, MadLib.JokerLists.Mult.Exponent, MadLib.JokerLists.Scaling.Mult },
            ['j_cry_stronghold']      = { MadLib.JokerLists.Mult.Add },
            ['j_cry_supercell']       = { MadLib.JokerLists.Chips.Add, MadLib.JokerLists.Mult.Add, MadLib.JokerLists.Chips.Multiply, MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.Money.Add },
            ['j_cry_sus']             = { MadLib.JokerLists.Generative.Card, MadLib.JokerLists.Destructive.Card, MadLib.JokerLists.Rank['j_cry_King'], MadLib.JokerLists.Suit['j_cry_Hearts'] },
            ['j_cry_swarm']           = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.HandType['j_cry_Flush Five'] },
            ['j_cry_sync_catalyst']   = { MadLib.JokerLists.Effect.Game },
            ['j_cry_tax_fraud']       = { MadLib.JokerLists.Money.Add },
            ['j_cry_tenebris']        = { MadLib.JokerLists.Money.Add, MadLib.JokerLists.Stats.JokerSlots },
            ['j_cry_translucent']     = { MadLib.JokerLists.Sell, MadLib.JokerLists.Generative.Joker },
            ['j_cry_treacherous']     = { MadLib.JokerLists.Chips.Add },
            ['j_cry_nebulous']        = { MadLib.JokerLists.Chips.Add },
            ['j_cry_words_cant_even'] = { MadLib.JokerLists.Mult.Multiply },
            ['j_cry_many_lost_minds'] = { MadLib.JokerLists.Chips.Add },
            ['j_cry_annihalation']    = { MadLib.JokerLists.Mult.Multiply },
            ['j_cry_trick_or_treat']  = { MadLib.JokerLists.Sell, MadLib.JokerLists.Generative.Joker },
            ['j_cry_tricksy']         = { MadLib.JokerLists.Chips.Add, MadLib.JokerLists.HandType['j_cry_Straight Flush'] },
            ['j_cry_triplet_rhythm']  = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.Rank['j_cry_3'] },
            ['j_cry_tropical_smoothie']   = { MadLib.JokerLists.Effect.Joker, MadLib.JokerLists.Meta, MadLib.JokerLists.Sell, MadLib.JokerLists.Food },
            ['j_cry_unity']           = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.HandType['j_cry_Flush House'] },
            ['j_cry_universe']        = { MadLib.JokerLists.Mult.Exponent },
            ['j_cry_universum']       = { MadLib.JokerLists.Effect.Game },
            ['j_cry_unjust_dagger']   = { MadLib.JokerLists.Destructive.Joker, MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.Scaling.Mult },
            ['j_cry_virgo']           = { MadLib.JokerLists.Scaling.Money, MadLib.JokerLists.Sell, MadLib.JokerLists.Generative.Joker, MadLib.JokerLists.HandType['j_cry_Pair'] },
            ['j_cry_wacky']           = { MadLib.JokerLists.Mult.Add, MadLib.JokerLists.HandType['j_cry_Flush House'] },
            ['j_cry_waluigi']         = { MadLib.JokerLists.Mult.Multiply },
            ['j_cry_wario']           = { MadLib.JokerLists.Money.Add },
            ['j_cry_wee_fib']         = { MadLib.JokerLists.Mult.Add, MadLib.JokerLists.Scaling.Mult },
            ['j_cry_wee_gaming']      = { MadLib.JokerLists.Retrigger.Card, MadLib.JokerLists.Rank['j_cry_2'] },
            ['j_cry_wheelhope']       = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.Scaling.Mult },
            ['j_cry_whip']            = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.Scaling.Mult, MadLib.JokerLists.Rank['j_cry_7'] },
            ['j_cry_wonka_bar']       = { MadLib.JokerLists.Sell, MadLib.JokerLists.Effect.Game },
            ['j_cry_wrapped']         = { MadLib.JokerLists.Generative.Joker, MadLib.JokerLists.Food },
            ['j_cry_wtf']             = { MadLib.JokerLists.Mult.Multiply },
            ['j_cry_zooble']          = { MadLib.JokerLists.Mult.Add, MadLib.JokerLists.Scaling.Mult, MadLib.JokerLists.HandType['j_cry_Straight'] },
            ['j_cry_queens_gambit']   = { MadLib.JokerLists.Rank['j_cry_Queen'], MadLib.JokerLists.HandType['j_cry_Straight Flush'], MadLib.JokerLists.Destructive.Card, MadLib.JokerLists.Generative.Joker },
            ['j_cry_cursor']          = { MadLib.JokerLists.Chips.Add, MadLib.JokerLists.Scaling.Chips },
            ['j_cry_longboi']         = { MadLib.JokerLists.Mult.Multiply, MadLib.JokerLists.Scaling.Mult, MadLib.JokerLists.Meta },
        },
        PointValues = {
            Editions = {
                ['e_cry_glitched']        = 10,
                ['e_cry_mosaic']          = 9,
                ['e_cry_oversaturated']   = 12,
                ['e_cry_fragile']         = 11,
                ['e_cry_golden']          = 8,
                ['e_cry_blurred']         = 7,
                ['e_cry_noisy']           = 9,
                ['e_cry_astral']          = 15,
                ['e_cry_jolly']           = 16,
                ['e_cry_double_sided']    = 10,
            },
            Enhancements = {
                ['e_cry_echo']        = 10,
                ['e_cry_light']       = 8,
                ['e_cry_abstract'] 	= 12,
            },
        },
        RarityValues = {

        },
        StickerLists = {
            ['cry_pinned'] = { MadLib.StickerLists.Bad },
            ['cry_banana'] = { MadLib.StickerLists.Bad, MadLib.StickerLists.Destructive }
        },
        Weights = {
            Boosters = {
                ['p_cry_meme_1']          = 4,
                ['p_cry_meme_two']        = 2,
                ['p_cry_meme_three'] 	    = 1,
                ['p_cry_code_normal_1']   = 4,
                ['p_cry_code_jumbo_1']    = 2,
                ['p_cry_code_mega_1']     = 1,
                ['p_cry_empowered']       = 0.3,
                ['p_cry_baneful_1']       = 0.5,
            },
            Editions = { -- idk for these
                ['e_cry_glitched']        = 0.5,
                ['e_cry_mosaic']          = 0.8,
                ['e_cry_oversaturated']   = 0.5,
                ['e_cry_fragile']         = 0.5,
                ['e_cry_golden']          = 0.5,
                ['e_cry_blurred']         = 0.4,
                ['e_cry_noisy']           = 0.4,
                ['e_cry_astral']          = 0.2,
                ['e_cry_jolly']           = 0.8,
                ['e_cry_double_sided']    = 0.4,
            },
            Enhancements = {
                ['m_cry_echo']        = 2,
                ['m_cry_light']       = 2,
                ['m_cry_abstract'] 	= 0.4,
            }
        },
    },
    init = function(c)
        -- Prefix
        local p = c.prefix..'_'



        -- transfers custom hand types - spectrum depends on mods added (goes by madlib's spectrum priority)
        local Bulwark       = p..'Bulwark'
        local Cluster       = p..'Clusterfuck'
        local UltimatePair  = p..'UltPair'
        local WholeDeck     = p..'WholeDeck'
        local None          = p..'None'

        local joker_poker_hands = {
            ['j_cry_adroit']              = { Bulwark },
            ['j_cry_bonkers']             = { Bulwark },
            ['j_cry_stronghold']          = { Bulwark },
            ['j_cry_fuckedup']            = { Cluster },
            ['j_cry_penetrating']         = { Cluster },
            ['j_cry_wtf']                 = { Cluster },
            ['j_cry_foolhardy']           = { UltimatePair },
            ['j_cry_treacherous']         = { UltimatePair },
            ['j_cry_clash']               = { UltimatePair },
            ['j_cry_words_cant_even']     = { WholeDeck },
            ['j_cry_many_lost_minds']     = { WholeDeck },
            ['j_cry_annihalation']        = { WholeDeck },
            ['j_cry_undefined']           = { None },
            ['j_cry_nebulous']            = { None },
            ['j_cry_the']                 = { None },
        }

        MadLib.loop_table(joker_poker_hands, function(k,v) table.insert(c.content.JokerCategories[k], MadLib.JokerLists.HandType[v]) end)

        local joker_ranks = {
            ['j_cry_wee_fib']             = { 'Ace', '2', '3', '5', '8'},
            ['j_cry_primus']              = { 'Ace', '2', '3', '5', '7'},
        }
        MadLib.transfer_to_new_table(joker_ranks,c.content.JokerRanks)

        -- Meme category for Meme Jokers
        MadLib.JokerLists.Meme = {
            'j_jolly',
            'j_mr_bones',
            'j_space',
            'j_obelisk',
        }
        local cryptid_memes = {
            'j_cry_m',
            'j_cry_happy',
            'j_cry_jimball',
            'j_cry_cube',
            'j_cry_krustytheclown',
            'j_cry_boredom',
            'j_cry_blurred',
            'j_cry_chad',
            'j_cry_sus',
            'j_cry_curse_sob',
            'j_cry_nice',
            'j_cry_filler',
            'j_cry_bonk',
            'j_cry_reverse',
            'j_cry_waluigi',
        }
        MadLib.loop_func(cryptid_memes, function(v) table.insert(MadLib.JokerLists.Meme, 'j_cry_'..v) end)

        -- Meme category for M/Jolly Jokers
        MadLib.JokerLists.M = {
            'j_jolly'
        }
        local cryptid_ms = {
            'j_cry_bubblem',
            'j_cry_bonk',
            'j_cry_doodlem',
            'j_cry_foodm',
            'j_cry_biggestm',
            'j_cry_jollysus',
            'j_cry_loopy',
            'j_cry_m',
            'j_cry_M',
            'j_cry_mstack',
            'j_cry_macabre',
            'j_cry_megg',
            'j_cry_longboi',
            'j_cry_notebook',
            'j_cry_mneon',
            'j_cry_reverse',
            'j_cry_sacrifice',
            'j_cry_scrabble',
            'j_cry_smallestm',
            'j_cry_mprime',
            'j_cry_virgo'
        }
        MadLib.loop_func(cryptid_ms, function(v) table.insert(MadLib.JokerLists.M, 'j_cry_'..v) end)

		return c
    end,
}
